# Generated by Django 2.0.6 on 2018-06-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180630_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='langerText',
            field=models.TextField(blank=True),
        ),
    ]
